---

- import_tasks: from_source.yml
  when: nginx_install_from == "source"  

- import_tasks: debian.yml
  when: nginx_install_from == "repo"  

- import_tasks: check.yml
  when: nginx_check | bool


# - name: turn server_tokens off
#   # 移除 server_tokens 前的 '#' 字元。
#   lineinfile: >
#     dest=/etc/nginx/nginx.conf
#     regexp="server_tokens off;"
#     insertafter="# server_tokens off;"
#     line="server_tokens off;"
#     state=present
#   notify: restart nginx

# vim:ft=yaml.ansible :
