user www-data;
worker_processes auto;
worker_rlimit_nofile 400000;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
  worker_connections 20000;
  # multi_accept on;
}

http {
  ##
  # Basic Settings
  ##
  # log_format main '$remote_addr - $remote_user [$time_local] '
  #                 '"$request" $status $bytes_sent '
  #                 '"$http_referer" "$http_user_agent" '
  #                 '"$gzip_ratio"';
  sendfile on;  # Enables efficient file transfers. Leave enabled for serving static files.
  tcp_nopush on;  # Optimizes TCP packets for sending large files. Leave as is unless specific requirements suggest otherwise.
  types_hash_max_size 2048;  # Limits the maximum size of the hash table for MIME types. Usually, the default value is sufficient.
  tcp_nodelay on;
  keepalive_timeout 65;

  set_real_ip_from 10.101.5.0/24;  # 
  real_ip_header X-Forwarded-For;
  # real_ip_header X-Real-IP; # Use X-Real-IP as client ip
  real_ip_recursive on;

  # Security Headers
  add_header X-Content-Type-Options nosniff;  # Prevents browsers from interpreting files as a different MIME type. Keep for security.
  add_header X-Frame-Options DENY;  # Prevents the site from being displayed in iframes. Keep for security unless needed otherwise.
  add_header X-XSS-Protection "1; mode=block";  # Protects against cross-site scripting (XSS) attacks. Keep for security.
  # don't send the nginx version number in error pages and Server header
  server_tokens off;
  proxy_hide_header X-Powered-By;
  proxy_hide_header Server;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  ##
  # SSL Settings
  ##
  ssl_protocols TLSv1.2 TLSv1.3;  # Enforces modern TLS protocols. Keep this for security purposes.
  ssl_prefer_server_ciphers on;  # Ensures the server's ciphers are preferred for secure connections. Leave as is.
  ssl_session_cache shared:SSL:10m;  # Enables caching of SSL sessions to improve performance on subsequent connections.
  ssl_session_timeout 10m;  # Sets the session cache timeout to 10 minutes. This is fine for most use cases.
  ssl_ciphers 'HIGH:!aNULL:!MD5';  # Specifies strong ciphers for SSL/TLS. Leave as is unless you need a specific set.

  ##
  # Logging Settings
  ##
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  ##
  # Gzip Settings
  ##
  gzip on;  # Enables Gzip compression for better performance. Keep enabled for most sites to reduce data size.
  gzip_vary on;  # Informs proxies that the response varies based on the request's Accept-Encoding header.
  gzip_proxied any;  # Enables Gzip for all proxied requests. Keep as is unless a specific case requires modification.
  # gzip_buffers 16 8k;
  gzip_comp_level 6;  # Defines the compression level. Level 6 is a good balance between speed and compression.
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  ##
  # Virtual Host Configs
  ##
  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}
