---

- name: View/Edit nginx nofile limits
  hosts: all 
  vars:
    nginx_nofile: 40000
  tasks:
    - name: Check if '-limit/-l' argument is provided
      fail:
        msg: "you must provides the -limit/-l argument to run this playbook"
      when: ansible_limit is not defined

    - name: Check if Nginx is running
      command: systemctl status nginx
      failed_when: false
      changed_when: false
      register: service_nginx_status

    - name: Report status of Nginx
      debug:
        msg: "Nginx is not installed {{service_nginx_status.rc}}"
      when: service_nginx_status.rc != 0

    - name: Nginx | Edit nofile limit 
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: '^worker_processes.*$'
        regexp: '^worker_rlimit_nofile'
        line: 'worker_rlimit_nofile {{nginx_nofile}};'
        state: present 
      tags: [edit, never]
      when: (service_nginx_status.rc == 0)
      notify: Nginx reload 

    - name: Nginx | Read nofile limits
      shell:
        cmd: |
          pgrep nginx | while read line; do printf "$line "; sudo prlimit -n -p "$line" | awk 'NR==2{print}' ; done
      register: out
      tags: [view]
      changed_when: no
      when: (service_nginx_status.rc == 0)

    - name: Nginx | Output nofile limits
      debug: 
        var=out.stdout_lines
      when: (out.stdout_lines is defined)
      tags: [view]

  handlers:
    - name: Nginx reload 
      command: nginx -s reload

# vim:set et sw=2 ts=2 ft=yaml.ansible:     
