- name: Config nvim
  hosts: all 
  become_user: "{{nvim_user}}"

  vars:
    config_git_repo: https://github.com/jyd519/vimfiles.git

  tasks:
    - name: Check if '-limit/-l' argument is provided
      fail:
        msg: "you must provides the -limit/-l argument to run this playbook"
      when: ansible_limit is not defined

    - name: clone git repo
      environment: "{{proxy_env}}"
      ansible.builtin.git:
        repo: "{{config_git_repo}}" 
        dest: ~/.vimgit
        version: lsp 

# vim:set et sw=2 ts=2 ft=yaml.ansible:     
