---

- name: playbook for testing
  hosts: all
  become: true
  #tasks:
  #  - name: Dump all variables
  #    ansible.builtin.debug:
  #      var: vars

  roles:
    - { role: bootstrap, tags: [bootstrap, never] }
    - { role: common, tags: ["common", never] }
    - { role: nvim, tags: ["nvim", never], become: true }
    - { role: nginx, tags: ["nginx", never] }
    - role: view-nofile
      vars:
        view_nofile_name: supervisor
      tags: [nofile, never]

# vim:set et sw=2 ts=2 ft=yaml.ansible:
