- name: multiple file copying methods
  hosts: all 
  tasks:
    - name: Check if '-limit/-l' argument is provided
      fail:
        msg: "you must provides the -limit/-l argument to run this playbook"
      when: ansible_limit is not defined

    # - name: Copy all yaml files
    #   copy:
    #     src: "{{ item }}"
    #     dest: "~/ansiblelab/"  # 结尾的/确保文件复制到目录中
    #   with_fileglob:
    #     - "*.yml"

    # - synchronize:
    #     src: ./roles
    #     dest: "~/ansiblelab2/"
    #     rsync_opts:
    #       - '--exclude=.git'

    # - name: Enable configuration
    #   file: >
    #     dest=/etc/nginx/sites-enabled/default
    #     src=/etc/nginx/sites-available/default
    #     state=link
    
    # - name: Copy index.html
    #   template: >
    #     src=index.html.j2
    #     dest=/usr/share/nginx/html/index.html
    
# vim:set et sw=2 ts=2 ft=yaml.ansible:     
