---

galaxy_info:
  author: Jiri Tyr
  description: A role that installs Supervisor.
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - system
dependencies:
  - config_encoder_filters
