---

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart pushgateway
  ansible.builtin.systemd:
    name: pushgateway
    state: restarted
    enabled: true

# vim:set et sw=2 ts=2 ft=yaml.ansible:
