---

- name: install common tools
  apt: 
    name: "{{ debain_common_tools }}"
    state: present
    update_cache: yes 
  when: ansible_os_family == "Debian"


# vim:set et ft=yaml.ansible sw=2 ts=2:
