---

- name: install neovim
  snap: name=nvim state=present classic=yes

# Configuration
- name: create nvim config directry 
  file:
    path: ~/.config/nvim
    state: directory 
  become_user: "{{nvim_user}}"

- name: configure nvim
  lineinfile:
    path: ~/.config/nvim/init.vim 
    line: "{{ item }}"
    state: present
    backup: no 
    create: yes
  become_user: "{{nvim_user}}"
  with_items:
    - "set background=light"
    - "set modeline"

- name: check if bashrc exists
  stat: path=~/.bashrc 
  become_user: "{{nvim_user}}"
  register: bashrc 

- name: create alias for nvim
  become_user: "{{nvim_user}}"
  lineinfile:
    path: ~/.bashrc 
    insertafter: "^alias\\s+"
    line: "alias vim='/snap/bin/nvim'"
    state: present
    backup: no 
  when: bashrc.stat.exists

# - name: Symlink vimrc
#   file:
#     src: "{{ dotfiles_home }}/roles/vim/files/vimrc"
#     dest: "{{dotfiles_user_home}}/.vimrc"
#     state: link
