---

# Install neovim 
- import_tasks: from_prerelease.yaml
  when: nvim_from == "prerelease"  

- name: Install neovim from repo
  apt:
    name: nvim 
    state: present 
    update_cache: yes
  when: nvim_from == "repo"  

- name: Install neovim from snap store
  snap: name=nvim state=present classic=yes
  when: nvim_from == "snap"  

# Configuration
- name: Create nvim config directry 
  file:
    path: ~/.config/nvim
    state: directory 

- name: Configure nvim
  lineinfile:
    path: ~/.config/nvim/init.vim 
    line: "{{ item }}"
    state: present
    backup: no 
    create: yes
  with_items:
    - "set background=light"
    - "set modeline"

- name: Check if bashrc exists
  stat: path=~/.bashrc 
  register: bashrc 

- name: Create alias for nvim
  lineinfile:
    path: ~/.bashrc 
    insertafter: "^alias\\s+"
    line: "alias vim='nvim'"
    state: present
    backup: no 
  when: bashrc.stat.exists

